apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://my-postgresql:5432/otus_helm_homework_db"
  SPRING_DATASOURCE_PASSWORD: "123456"
  SPRING_DATASOURCE_USERNAME: "pguser"