apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
data:
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.open-in-view: "false"
  management.endpoint.health.probes.enabled: "true"
  management.endpoints.web.exposure.include: health,info
  management.endpoint.health.show-details: always
  management.server.port: "8081"